local dialog = {
	['Project Lazarus'] = {
		['Valium'] = {
			['poknowledge'] = {
				['The Warrens'] = 'warrens',
				['Field of Bone'] = 'fieldofbone',
				['Timorous Deep'] = 'timorous',
				['Tower of Frozen Shadow'] = 'frozenshadow',
				['Grimling Forest'] = 'grimling',
				['Trakanon\'s Teeth'] = 'trakanon',
				['Guk Top'] = 'guktop',
				['Gunthak'] = 'gunthak',
				['Highkeep'] = 'highkeep',
				['Velketor\'s Labyrinth '] = 'velketor',
				['Vex Thal'] = 'vexthal',
				['Wakening Lands'] = 'wakening',
				['Wall of Slaughter'] = 'wallofslaughter',
				['Kael Drakkal'] = 'kael',
				['Kaesora'] = 'kaesora',
				['Karnor\'s Castle'] = 'karnor',
				['Kurn\'s Tower'] = 'kurn',
				['Lake of Ill Omen'] = 'lakeofillomen',
				['Lavastorm Mountains'] = 'lavastorm',
				['Maiden\'s Eye'] = 'maiden',
				['Iceclad Ocean'] = 'iceclad',
				['Mistmoore Castle'] = 'mistmoore',
				['Jagged Pine Forrest'] = 'jaggedpine',
				['Nadox'] = 'nadox',
				['Emerald Jungle'] = 'emeraldjungle',
				['Najena'] = 'najena',
				['Estate of Unrest'] = 'unrest',
				['Natimbi'] = 'natimbi',
				['Erudin'] = 'erudnext',
				['Necropolis'] = 'necropolis',
				['Veksar'] = 'veksar',
				['North Karana'] = 'northkarana',
				['Umbral Plains'] = 'umbral',
				['Echo Caverns'] = 'echo',
				['Mines of Nurga'] = 'nurga',
				['Twilight Sea'] = 'twilight',
				['Ocean of Tears'] = 'oot',
				['Western Wastes'] = 'westwastes',
				['Paludal Caverns'] = 'paludal',
				['Freeport Temple'] = 'freeporttemple',
				['Split Paw'] = 'paw',
				['Warsliks Wood'] = 'warslikswood',
				['Permafrost'] = 'permafrost',
				['Guk Bottom'] = 'gukbottom',
				['Plane of Air'] = 'poair',
				['Fungus Grove'] = 'fungusgrove',
				['Plane of Disease'] = 'podisease',
				['Tower of Solusek Ro'] = 'solrotower',
				['Plane of Eartha'] = 'poeartha',
				['Hole'] = 'hole',
				['Plane of Earthb'] = 'poearthb',
				['South Ro'] = 'sro',
				['Plane of Fire'] = 'pofire',
				['Halls of Honor'] = 'hohonora',
				['Plane of Growth'] = 'growthplane',
				['Abysmal Sea'] = 'abysmal',
				['Plane of Innovation'] = 'poinnovation',
				['Acrylia'] = 'acrylia',
				['Plane of Justice'] = 'pojustice',
				['Arena'] = 'arena',
				['Plane of Mischief'] = 'mischiefplane',
				['Barindu'] = 'barindu',
				['Plane of Nightmare'] = 'ponightmare',
				['Befallen'] = 'befallen',
				['Plane of Storms'] = 'postorms',
				['Blackburrow'] = 'blackburrow',
				['Plane of Tactics'] = 'potactics',
				['Bastion of Thunder'] = 'bothunder',
				['Plane of Valor'] = 'povalor',
				['Burning Wood\'s'] = 'burningwood',
				['Plane of Water'] = 'powater',
				['Cazic Thule'] = 'cazicthule',
				['Qeynos Hills'] = 'qeytoqrg',
				['Charasis'] = 'charasis',
				['Qinimi'] = 'qinimi',
				['Chardok'] = 'chardok',
				['Qeynos'] = 'qrg',
				['City of Mist'] = 'citymist',
				['Riwwi'] = 'riwwi',
				['Cobalt Scar'] = 'cobaltscar',
				['Runnyeye'] = 'runnyeye',
				['Crypt of Decay'] = 'codecay',
				['Scarlet Desert'] = 'scarlet',
				['Commons'] = 'commons',
				['Sebilis'] = 'sebilis',
				['Crushbone'] = 'crushbone',
				['Shadowhaven'] = 'shadowhaven',
				['Crystal Caverns'] = 'crystal',
				['Shar Vahl'] = 'sharvahl',
				['Dalnir'] = 'dalnir',
				['Skyfire'] = 'skyfire',
				['Dawnshroud'] = 'dawnshroud',
				['Sky Shrine'] = 'skyshrine',
				['Dranik'] = 'dranik',
				['Solusek A'] = 'soldunga',
				['Dranik\'s Scar'] = 'draniksscar',
				['Solusek B'] = 'soldungb',
				['Dreadlands'] = 'dreadlands',
				['Solusek C'] = 'soldungc',
				['Dulak'] = 'dulak',
				['Ferubi'] = 'ferubi',
				['Ssraeshza Temple'] = 'ssratemple',
				['North Ro'] = 'nro',
				['Steamfont Mountains'] = 'steamfont',
				['Thurgadin'] = 'thurgadina',
				['Stonebrunt Mountains'] = 'stonebrunt',
				['None'] = 'None',
				['The Grey'] = 'thegrey',
			},
		},
		['A Priest of Luclin'] = {
			['poknowledge'] = {
				['Summon Corpse'] = 'summon',
			},
		},
		['Rokuth'] = {
			['allzones'] = {
				['Leave Expedition'] = 'leave',
				['Enter Expedition'] = 'enter',
			},
		},
		['Guardian Bomawyn'] = {
			['poknowledge'] = {
				['Orb of Mastery'] = 'Orb of Mastery',
			},
		},
		['Castlen Drewe'] = {
			['poknowledge'] = {
				['quest'] = 'quest',
			},
		},
		['Montolio'] = {
			['poknowledge'] = {
				['days'] = 'days',
				['deal'] = 'deal',
			},
		},
		['Larat Grundror'] = {
			['poknowledge'] = {
				['lockouts'] = 'lockouts',
			},
		},
		['Dronk'] = {
			['poknowledge'] = {
				['efforts'] = 'efforts',
				['task'] = 'task',
			},
		},
		['Guardian Norerd'] = {
			['poknowledge'] = {
				['Spear of Fate'] = 'Spear of Fate',
			},
		},
		['Celli'] = {
			['bazaar'] = {
				['Plane of Knowledge'] = 'Plane of Knowledge',
				['None'] = 'None',
				['Temple of Marr'] = 'Temple of Marr',
			},
		},
		['Guardian Erohach'] = {
			['poknowledge'] = {
				['Fiery Defender'] = 'Fiery Defender',
			},
		},
		['Lazy Lady Linda'] = {
			['allzones'] = {
				['None'] = 'None',
				['Enter AFK PoK'] = 'enter',
			},
		},
		['Mavis'] = {
			['poknowledge'] = {
				['Plane of Hate A'] = 'Hate-A',
				['Plane of Fear'] = 'Fear',
				['None'] = 'None',
				['Plane of Sky'] = 'sky',
				['Plane of Hate B'] = 'Hate-B',
			},
		},
		['Azray Velfor'] = {
			['poknowledge'] = {
				['find'] = 'find',
				['Cheryth Hryk'] = 'Cheryth Hryk',
				['help'] = 'help',
				['assist'] = 'assist',
				['Gift of Knowledge'] = 'Gift of Knowledge',
			},
		},
		['Vierna'] = {
			['poknowledge'] = {
				['revenge'] = 'revenge',
			},
		},
		['Klonopin'] = {
			['freeporttemple'] = {
				['The Warrens'] = 'warrens',
				['Thurgadin'] = 'thurgadina',
				['Timorous Deep'] = 'timorous',
				['Fungus Grove'] = 'fungusgrove',
				['Grimling Forest'] = 'grimling',
				['Guk Bottom'] = 'gukbottom',
				['Guk Top'] = 'guktop',
				['Gunthak'] = 'gunthak',
				['Highkeep'] = 'highkeep',
				['Velketor\'s Labyrinth '] = 'velketor',
				['Vex Thal'] = 'vexthal',
				['Wakening Lands'] = 'wakening',
				['Wall of Slaughter'] = 'wallofslaughter',
				['Kael Drakkal'] = 'kael',
				['Kaesora'] = 'kaesora',
				['Karnor\'s Castle'] = 'karnor',
				['Kurn\'s Tower'] = 'kurn',
				['Lake of Ill Omen'] = 'lakeofillomen',
				['Lavastorm Mountains'] = 'lavastorm',
				['Maiden\'s Eye'] = 'maiden',
				['Emerald Jungle'] = 'emeraldjungle',
				['Mistmoore Castle'] = 'mistmoore',
				['Jagged Pine Forrest'] = 'jaggedpine',
				['Nadox'] = 'nadox',
				['Halls of Honor'] = 'hohonora',
				['Najena'] = 'najena',
				['Erudin'] = 'erudnext',
				['Natimbi'] = 'natimbi',
				['Veksar'] = 'veksar',
				['Necropolis'] = 'necropolis',
				['Iceclad Ocean'] = 'iceclad',
				['North Karana'] = 'northkarana',
				['Plane of Knowledge'] = 'poknowledge',
				['Umbral Plains'] = 'umbral',
				['Mines of Nurga'] = 'nurga',
				['Echo Caverns'] = 'echo',
				['Ocean of Tears'] = 'oot',
				['Western Wastes'] = 'westwastes',
				['Paludal Caverns'] = 'paludal',
				['Twilight Sea'] = 'twilight',
				['Split Paw'] = 'paw',
				['Warsliks Wood'] = 'warslikswood',
				['Permafrost'] = 'permafrost',
				['North Ro'] = 'nro',
				['Plane of Air'] = 'poair',
				['Trakanon\'s Teeth'] = 'trakanon',
				['Plane of Disease'] = 'podisease',
				['Tower of Solusek Ro'] = 'solrotower',
				['Plane of Eartha'] = 'poeartha',
				['Hole'] = 'hole',
				['Plane of Earthb'] = 'poearthb',
				['South Ro'] = 'sro',
				['Plane of Fire'] = 'pofire',
				['Estate of Unrest'] = 'unrest',
				['Plane of Growth'] = 'growthplane',
				['Abysmal Sea'] = 'abysmal',
				['Plane of Innovation'] = 'poinnovation',
				['Acrylia'] = 'acrylia',
				['Plane of Justice'] = 'pojustice',
				['Arena'] = 'arena',
				['Plane of Mischief'] = 'mischiefplane',
				['Barindu'] = 'barindu',
				['Plane of Nightmare'] = 'ponightmare',
				['Befallen'] = 'befallen',
				['Plane of Storms'] = 'postorms',
				['Blackburrow'] = 'blackburrow',
				['Plane of Tactics'] = 'potactics',
				['Bastion of Thunder'] = 'bothunder',
				['Plane of Valor'] = 'povalor',
				['Burning Wood\'s'] = 'burningwood',
				['Plane of Water'] = 'powater',
				['Cazic Thule'] = 'cazicthule',
				['Qeynos Hills'] = 'qeytoqrg',
				['Charasis'] = 'charasis',
				['Qinimi'] = 'qinimi',
				['Chardok'] = 'chardok',
				['Qeynos'] = 'qrg',
				['City of Mist'] = 'citymist',
				['Riwwi'] = 'riwwi',
				['Cobalt Scar'] = 'cobaltscar',
				['Runnyeye'] = 'runnyeye',
				['Crypt of Decay'] = 'codecay',
				['Scarlet Desert'] = 'scarlet',
				['Commons'] = 'commons',
				['Sebilis'] = 'sebilis',
				['Crushbone'] = 'crushbone',
				['Shadowhaven'] = 'shadowhaven',
				['Crystal Caverns'] = 'crystal',
				['Shar Vahl'] = 'sharvahl',
				['Dalnir'] = 'dalnir',
				['Skyfire'] = 'skyfire',
				['Dawnshroud'] = 'dawnshroud',
				['Sky Shrine'] = 'skyshrine',
				['Dranik'] = 'dranik',
				['Solusek A'] = 'soldunga',
				['Dranik\'s Scar'] = 'draniksscar',
				['Solusek B'] = 'soldungb',
				['Dreadlands'] = 'dreadlands',
				['Solusek C'] = 'soldungc',
				['Dulak'] = 'dulak',
				['Field of Bone'] = 'fieldofbone',
				['Ssraeshza Temple'] = 'ssratemple',
				['None'] = 'None',
				['Steamfont Mountains'] = 'steamfont',
				['Tower of Frozen Shadow'] = 'frozenshadow',
				['Stonebrunt Mountains'] = 'stonebrunt',
				['Ferubi'] = 'ferubi',
				['The Grey'] = 'thegrey',
			},
		},
		['Magus Wenla'] = {
			['nedaria'] = {
				['Common Lands'] = 'commonlands',
				['Natimbi'] = 'natimbi',
				['Butcher Block'] = 'butcherblock',
				['Abysmal Sea'] = 'Abysmal Sea',
				['None'] = 'None',
				['Everfrost'] = 'everfrost',
				['North Ro'] = 'North Ro',
				['South Ro'] = 'South Ro',
			},
		},
		['Magus Tira'] = {
			['butcherblock'] = {
				['Common Lands'] = 'commonlands',
				['None'] = 'None',
				['Everfrost'] = 'everfrost',
				['North Ro'] = 'North Ro',
				['South Ro'] = 'South Ro',
			},
		},
		['Magus Zeir'] = {
			['ecommons'] = {
				['Everfrost'] = 'everfrost',
				['Butcher Block'] = 'butcherblock',
				['None'] = 'None',
				['North Ro'] = 'North Ro',
				['South Ro'] = 'South Ro',
			},
		},
		['Magus Delin'] = {
			['everfrost'] = {
				['Common Lands'] = 'commonlands',
				['Butcher Block'] = 'butcherblock',
				['None'] = 'None',
				['North Ro'] = 'North Ro',
				['South Ro'] = 'South Ro',
			},
		},
		['Magus Arindri'] = {
			['nro'] = {
				['Everfrost'] = 'everfrost',
				['Butcher Block'] = 'butcherblock',
				['None'] = 'None',
				['Common Lands'] = 'commonlands',
				['South Ro'] = 'South Ro',
			},
		},
		['Magus Jerira'] = {
			['sro'] = {
				['Common Lands'] = 'commonlands',
				['Butcher Block'] = 'butcherblock',
				['None'] = 'None',
				['North Ro'] = 'North Ro',
				['Everfrost'] = 'everfrost',
			},
		},
		['Translocator Fithop'] = {
			['butcherblock'] = {
				['None'] = 'None',
				['Ocean of Tears'] = 'Travel to the Ocean of Tears',
			},
		},
		['Grynik'] = {
			['poknowledge'] = {
				['Rez Corpse'] = 'cost',
				['Resurrect'] = 'resurrect',
			},
		},
		['Translocator Gethia'] = {
			['butcherblock'] = {
				['None'] = 'None',
				['Ocean of Tears'] = 'Travel to the Ocean of Tears',
			},
		},
		['Translocator Deela'] = {
			['timorous'] = {
				['None'] = 'None',
				['Butcher Block'] = 'travel to butcherblock',
			},
		},
		['Soulbinder Jera'] = {
			['allzones'] = {
				['bind your soul'] = 'bind your soul',
			},
		},
		['Translocator Narrik'] = {
			['oot'] = {
				['East Freeport'] = 'travel to the Freeport',
				['Butcher Block'] = 'travel to butcherblock',
				['None'] = 'None',
			},
		},
		['Amphrtxi'] = {
			['poknowledge'] = {
				['30 DC -> 10 AA'] = 'convert DC 10',
				['10 AA - > 30 DC'] = 'convert AA 10',
				['1 AA - > 3 DC'] = 'convert AA 1',
				['convert'] = 'convert',
				['50 AA - > 150 DC'] = 'convert AA 50',
				['6 DC -> 2 AA'] = 'convert DC 2',
				['15 DC -> 5 AA'] = 'convert DC 5',
				['150 DC -> 50 AA'] = 'convert DC 50',
				['20 AA - > 60 DC'] = 'convert AA 20',
				['60 DC -> 20 AA'] = 'convert DC 20',
				['2 AA - > 6 DC'] = 'convert AA 2',
				['5 AA - > 15 DC'] = 'convert AA 5',
				['3 DC -> 1 AA'] = 'convert DC 1',
			},
		},
		['Fipnoc Birribit'] = {
			['poknowledge'] = {
				['more'] = 'more',
				['interesting ore'] = 'interesting ore',
				['information'] = 'information',
				['deal with'] = 'deal with',
				['work'] = 'work',
			},
		},
		['Translocator Setikan'] = {
			['freeporte'] = {
				['None'] = 'None',
				['Ocean of Tears'] = 'Travel to the Ocean of Tears',
			},
		},
		['Markoris'] = {
			['poknowledge'] = {
				['cost'] = 'cost',
				['train'] = 'train',
			},
		},
		['Guardian Adiasean'] = {
			['poknowledge'] = {
				['Staff of the Four'] = 'Staff of the Four',
			},
		},
		['Bookkeep Gerald'] = {
			['poknowledge'] = {
				['View Books'] = 'view',
				['Delete'] = 'delete',
				['View Class'] = 'view class',
				['Add'] = 'add',
				['Hide'] = 'hide',
			},
		},
		['Magus Alaria'] = {
			['poknowledge'] = {
				['Common Lands'] = 'commonlands',
				['Butcher Block'] = 'butcherblock',
				['Nedaria\'s Landing'] = 'nedaria\'s landing',
				['None'] = 'None',
				['Everfrost'] = 'everfrost',
				['North Ro'] = 'North Ro',
				['South Ro'] = 'South Ro',
			},
		},
		['Rubrae'] = {
			['allzones'] = {
				['2 Hours'] = '2 Hours',
				['3 Hours'] = '3 Hours',
				['4 Hours'] = '4 Hours',
				['5 Hours'] = '5 Hours',
				['6 Hours'] = '6 Hours',
				['8 Hours'] = '8 Hours',
				['advanced'] = 'advanced',
				['price'] = 'price',
				['10 Hours'] = '10 Hours',
				['buffs'] = 'buffs',
			},
		},
	},
	['Live'] = {

	},
}
return dialog
