local dialog = {
	['Project Lazarus'] = {
		['Magus Alaria'] = {
			['poknowledge'] = {
				['Common Lands']='commonlands',
				['Butcher Block']='butcherblock',
				['Nedaria\'s Landing']='nedaria\'s landing',
				['North Ro']='North Ro',
				['South Ro']='South Ro',
				['Everfrost']='everfrost',
				['None']='None',
			},
		},
		['Valium'] = {
			['poknowledge'] = {
				['None']="None",
				['Abysmal Sea']="abysmal",
				['Acrylia']="acrylia",
				['Arena']="arena",
				['Barindu']="barindu",
				['Befallen']="befallen",
				['Blackburrow']="blackburrow",
				['Bastion of Thunder']="bothunder",
				['Burning Wood\'s']="burningwood",
				['Cazic Thule']="cazicthule",
				['Charasis']="charasis",
				['Chardok']="chardok",
				['City of Mist']="citymist",
				['Cobalt Scar']="cobaltscar",
				['Crypt of Decay']="codecay",
				['Commons']="commons",
				['Crushbone']="crushbone",
				['Crystal Caverns']="crystal",
				['Dalnir']="dalnir",
				['Dawnshroud']="dawnshroud",
				['Dranik']="dranik",
				['Dranik\'s Scar']="draniksscar",
				['Dreadlands']="dreadlands",
				['Dulak']="dulak",
				['Echo Caverns']="echo",
				['Emerald Jungle']="emeraldjungle",
				['Erudin']="erudnext",
				['Estate of Unrest']="unrest",
				['Ferubi']="ferubi",
				['Field of Bone']="fieldofbone",
				['Freeport Temple']="freeporttemple",
				['Fungus Grove']="fungusgrove",
				['Grimling Forest']="grimling",
				['Guk Bottom']="gukbottom",
				['Guk Top']="guktop",
				['Gunthak']="gunthak",
				['Highkeep']="highkeep",
				['Halls of Honor']="hohonora",
				['Hole']="hole",
				['Iceclad Ocean']="iceclad",
				['Jagged Pine Forrest']="jaggedpine",
				['Kael Drakkal']="kael",
				['Kaesora']="kaesora",
				['Karnor\'s Castle']="karnor",
				['Kurn\'s Tower']="kurn",
				['Lake of Ill Omen']="lakeofillomen",
				['Lavastorm Mountains']="lavastorm",
				['Maiden\'s Eye']="maiden",
				['Mistmoore Castle']="mistmoore",
				['Nadox']="nadox",
				['Najena']="najena",
				['Natimbi']="natimbi",
				['Necropolis']="necropolis",
				['North Karana']="northkarana",
				['North Ro']="nro",
				['Mines of Nurga']="nurga",
				['Ocean of Tears']="oot",
				['Paludal Caverns']="paludal",
				['Split Paw']="paw",
				['Permafrost']="permafrost",
				['Plane of Air']="poair",
				['Plane of Disease']="podisease",
				['Plane of Eartha']="poeartha",
				['Plane of Earthb']="poearthb",
				['Plane of Fire']="pofire",
				['Plane of Growth']="growthplane",
				['Plane of Innovation']="poinnovation",
				['Plane of Justice']="pojustice",
				['Plane of Mischief']="mischiefplane",
				['Plane of Nightmare']="ponightmare",
				['Plane of Storms']="postorms",
				['Plane of Tactics']="potactics",
				['Plane of Valor']="povalor",
				['Plane of Water']="powater",
				['Qeynos Hills']="qeytoqrg",
				['Qinimi']="qinimi",
				['Qeynos']="qrg",
				['Riwwi']="riwwi",
				['Runnyeye']="runnyeye",
				['Scarlet Desert']="scarlet",
				['Sebilis']="sebilis",
				['Shadowhaven']="shadowhaven",
				['Shar Vahl']="sharvahl",
				['Skyfire']="skyfire",
				['Sky Shrine']="skyshrine",
				['Solusek A']="soldunga",
				['Solusek B']="soldungb",
				['Solusek C']="soldungc",
				['South Ro']="sro",
				['Ssraeshza Temple']="ssratemple",
				['Steamfont Mountains']="steamfont",
				['Stonebrunt Mountains']="stonebrunt",
				['The Grey']="thegrey",
				['The Warrens']="warrens",
				['Thurgadin']="thurgadina",
				['Timorous Deep']="timorous",
				['Tower of Frozen Shadow']="frozenshadow",
				['Tower of Solusek Ro']="solrotower",
				['Trakanon\'s Teeth']="trakanon",
				['Twilight Sea']="twilight",
				['Umbral Plains']="umbral",
				['Veksar']="veksar",
				['Velketor\'s Labyrinth ']="velketor",
				['Vex Thal']="vexthal",
				['Wakening Lands']="wakening",
				['Wall of Slaughter']="wallofslaughter",
				['Warsliks Wood']="warslikswood",
				['Western Wastes']="westwastes",
			},
		},
		['Celli'] = {
			['bazaar'] ={
				['None'] = 'None',
				['Temple of Marr'] = 'Temple of Marr',
				['Plane of Knowledge'] = 'Plane of Knowledge',
			},
		},
		['Lazy Lady Linda'] = {
			['poknowledge'] = {
				['None'] = 'None',
				['Enter AFK PoK'] = 'enter',
			},
		},
		['Mavis'] = {
			['poknowledge'] ={
					['Plane of Hate A']='Hate-A',
					['Plane of Fear']='Fear',
					['Plane of Sky']='sky',
					['Plane of Hate B']='Hate-B',
					['None']='None',
			},
		},
		['Klonopin'] = {
			['freeporttemple'] = {
				['None']="None",
				['Abysmal Sea']="abysmal",
				['Acrylia']="acrylia",
				['Arena']="arena",
				['Barindu']="barindu",
				['Befallen']="befallen",
				['Blackburrow']="blackburrow",
				['Bastion of Thunder']="bothunder",
				['Burning Wood\'s']="burningwood",
				['Cazic Thule']="cazicthule",
				['Charasis']="charasis",
				['Chardok']="chardok",
				['City of Mist']="citymist",
				['Cobalt Scar']="cobaltscar",
				['Crypt of Decay']="codecay",
				['Commons']="commons",
				['Crushbone']="crushbone",
				['Crystal Caverns']="crystal",
				['Dalnir']="dalnir",
				['Dawnshroud']="dawnshroud",
				['Dranik']="dranik",
				['Dranik\'s Scar']="draniksscar",
				['Dreadlands']="dreadlands",
				['Dulak']="dulak",
				['Echo Caverns']="echo",
				['Emerald Jungle']="emeraldjungle",
				['Erudin']="erudnext",
				['Estate of Unrest']="unrest",
				['Ferubi']="ferubi",
				['Field of Bone']="fieldofbone",
				['Fungus Grove']="fungusgrove",
				['Grimling Forest']="grimling",
				['Guk Bottom']="gukbottom",
				['Guk Top']="guktop",
				['Gunthak']="gunthak",
				['Highkeep']="highkeep",
				['Halls of Honor']="hohonora",
				['Hole']="hole",
				['Iceclad Ocean']="iceclad",
				['Jagged Pine Forrest']="jaggedpine",
				['Kael Drakkal']="kael",
				['Kaesora']="kaesora",
				['Karnor\'s Castle']="karnor",
				['Kurn\'s Tower']="kurn",
				['Lake of Ill Omen']="lakeofillomen",
				['Lavastorm Mountains']="lavastorm",
				['Maiden\'s Eye']="maiden",
				['Mistmoore Castle']="mistmoore",
				['Nadox']="nadox",
				['Najena']="najena",
				['Natimbi']="natimbi",
				['Necropolis']="necropolis",
				['North Karana']="northkarana",
				['North Ro']="nro",
				['Mines of Nurga']="nurga",
				['Ocean of Tears']="oot",
				['Paludal Caverns']="paludal",
				['Split Paw']="paw",
				['Permafrost']="permafrost",
				['Plane of Air']="poair",
				['Plane of Disease']="podisease",
				['Plane of Eartha']="poeartha",
				['Plane of Earthb']="poearthb",
				['Plane of Fire']="pofire",
				['Plane of Growth']="growthplane",
				['Plane of Innovation']="poinnovation",
				['Plane of Justice']="pojustice",
				['Plane of Knowledge']="poknowledge",
				['Plane of Mischief']="mischiefplane",
				['Plane of Nightmare']="ponightmare",
				['Plane of Storms']="postorms",
				['Plane of Tactics']="potactics",
				['Plane of Valor']="povalor",
				['Plane of Water']="powater",
				['Qeynos Hills']="qeytoqrg",
				['Qinimi']="qinimi",
				['Qeynos']="qrg",
				['Riwwi']="riwwi",
				['Runnyeye']="runnyeye",
				['Scarlet Desert']="scarlet",
				['Sebilis']="sebilis",
				['Shadowhaven']="shadowhaven",
				['Shar Vahl']="sharvahl",
				['Skyfire']="skyfire",
				['Sky Shrine']="skyshrine",
				['Solusek A']="soldunga",
				['Solusek B']="soldungb",
				['Solusek C']="soldungc",
				['South Ro']="sro",
				['Ssraeshza Temple']="ssratemple",
				['Steamfont Mountains']="steamfont",
				['Stonebrunt Mountains']="stonebrunt",
				['The Grey']="thegrey",
				['The Warrens']="warrens",
				['Thurgadin']="thurgadina",
				['Timorous Deep']="timorous",
				['Tower of Frozen Shadow']="frozenshadow",
				['Tower of Solusek Ro']="solrotower",
				['Trakanon\'s Teeth']="trakanon",
				['Twilight Sea']="twilight",
				['Umbral Plains']="umbral",
				['Veksar']="veksar",
				['Velketor\'s Labyrinth ']="velketor",
				['Vex Thal']="vexthal",
				['Wakening Lands']="wakening",
				['Wall of Slaughter']="wallofslaughter",
				['Warsliks Wood']="warslikswood",
				['Western Wastes']="westwastes",
			},
		},
		['Magus Wenla'] = {
			['nedaria'] = {
				['None'] = 'None',
				['Abysmal Sea']='Abysmal Sea',
				['Common Lands']='commonlands',
				['Butcher Block']='butcherblock',
				['Natimbi']='natimbi',
				['North Ro']='North Ro',
				['South Ro']='South Ro',
				['Everfrost']='everfrost',
			},
		},
		['Magus Tira'] = {
			['butcherblock'] = {
				['None'] = 'None',
				-- ['Abysmal Sea']='Abysmal Sea',
				['Common Lands']='commonlands',
				-- ['Butcher Block']='butcherblock',
				-- ['Natimbi']='natimbi',
				['North Ro']='North Ro',
				['South Ro']='South Ro',
				['Everfrost']='everfrost',
			},
		},
		['Magus Zeir'] = {
			['ecommons'] = {
				['None'] = 'None',
				-- ['Abysmal Sea']='Abysmal Sea',
				-- ['Common Lands']='commonlands',
				['Butcher Block']='butcherblock',
				-- ['Natimbi']='natimbi',
				['North Ro']='North Ro',
				['South Ro']='South Ro',
				['Everfrost']='everfrost',
			},
		},
		['Magus Delin'] = {
			['everfrost'] = {
				['None'] = 'None',
				-- ['Abysmal Sea']='Abysmal Sea',
				['Common Lands']='commonlands',
				['Butcher Block']='butcherblock',
				-- ['Natimbi']='natimbi',
				['North Ro']='North Ro',
				['South Ro']='South Ro',
				-- ['Everfrost']='everfrost',
			},
		},
		['Magus Arindri'] = {
			['nro'] = {
				['None'] = 'None',
				-- ['Abysmal Sea']='Abysmal Sea',
				['Common Lands']='commonlands',
				['Butcher Block']='butcherblock',
				-- ['Natimbi']='natimbi',
				-- ['North Ro']='North Ro',
				['South Ro']='South Ro',
				['Everfrost']='everfrost',
			},	
		},
		['Magus Jerira'] = {
			['sro'] = {
				['None'] = 'None',
				-- ['Abysmal Sea']='Abysmal Sea',
				['Common Lands']='commonlands',
				['Butcher Block']='butcherblock',
				-- ['Natimbi']='natimbi',
				['North Ro']='North Ro',
				-- ['South Ro']='South Ro',
				['Everfrost']='everfrost',
			},
		},
		['Translocator Fithop'] = {
			['butcherblock'] = {
			['Ocean of Tears']="Travel to the Ocean of Tears",
			['None']='None',
			},
		},
		['Translocator Gethia'] = {
			['butcherblock'] = {
			['Ocean of Tears']="Travel to the Ocean of Tears",
			['None']='None',
			},
		},		
		-- Translocator Deela (Timorous Deep)
		['Translocator Deela'] = {
			['timorous'] = {
				['Butcher Block']="travel to butcherblock",
				['None']='None',
			},
		},				
		-- Translocator Narrik (Ocean of Tears)
		['Translocator Narrik'] = {
			['oot'] = {
				['Butcher Block']="travel to butcherblock",
				['East Freeport']="travel to the Freeport",
				['None']='None',
			},
		},
		-- Translocator Setikan (East Freeport Docks)
		['Translocator Setikan'] = {
			['freeporte'] = {
			['Ocean of Tears']="Travel to the Ocean of Tears",
			['None']='None',
			},
		},
	},	
}
return dialog
