return {
	['Live'] = {
		['Anibarean of the Light'] = {
			['poknowledge'] = {
				['enter the chapel'] = '/say enter the chapel',
			},
		},
		['Mercenary Captain Cecille'] = {
			['poknowledge'] = {
				['help'] = '/say help',
			},
		},
		['Rytan'] = {
			['tutorialb'] = {
				['Review'] = '/say review',
				['Blessing'] = '/say blessed',
			},
			['allzones'] = {},
		},
		['Sage Valgond'] = {
			['allzones'] = {},
			['poknowledge'] = {
				['test subject'] = '/say test subject',
				['teleportation magic'] = '/say teleportation magic',
			},
		},
		['Alerynril the Loyal'] = {
			['allzones'] = {},
			['poknowledge'] = {
				['holding'] = '/say holding',
				['marketplace'] = '/say marketplace',
				['defenders of Norrath'] = '/say defenders of Norrath',
				['shield'] = '/say shield',
			},
		},
		['Brewmaster Teremun'] = {
			['crescent'] = {
				['Brodder'] = '/say Brodder',
				['interested'] = '/say interested',
				['brews'] = '/say brews',
				['Lost Diaries'] = '/say lost diaries',
			},
		},
		['Sage Vonglor'] = {
			['guildlobby'] = {
				['test subject'] = '/say test subject',
				['teleportation magic'] = '/say teleportation magic',
			},
			['allzones'] = {},
		},
		['Matrum Geerlok'] = {
			['crescent'] = {
				['assembly'] = '/say assembly',
				['operation'] = '/say operation',
				['seven'] = '/say seven',
				['Lubricant'] = '/say lubricant',
				['Caltrops'] = '/say Caltrops',
				['instructions'] = '/say instructions',
				['way'] = '/say way',
				['Roboboar'] = '/say Roboboar',
				['durable grinding blade'] = '/say durable grinding blade',
				['Class V'] = '/say Class V',
				['Bone Rods'] = '/say Bone Rods',
				['Device'] = '/say device',
				['Ready to start'] = '/say Ready to start',
				['Make'] = '/say make',
				['work'] = '/say work',
				['training'] = '/say training',
				['Augment'] = '/say augment',
				['improved'] = '/say improved',
				['ideas'] = '/say ideas',
			},
		},
		['Vivian the True'] = {
			['poknowledge'] = {
				['new to the world'] = '/say new to the world',
			},
		},
		['Akins'] = {
			['crescent'] = {
				['learn'] = '/say learn',
				['passed'] = '/say passed',
			},
		},
		['Secalna Galnor'] = {
			['poknowledge'] = {
				['send'] = '/say send',
			},
		},
		['Rashere'] = {
			['tutorialb'] = {
				['Bind'] = '/say bind my soul',
			},
			['allzones'] = {},
		},
		['Vacurasa of the Dark'] = {
			['poknowledge'] = {
				['enter the chapel'] = '/say enter the chapel',
			},
		},
		['Frizznik'] = {
			['tutorialb'] = {
				['Rat Steaks'] = '/say rat steaks',
			},
			['allzones'] = {},
		},
		['Devin Traical'] = {
			['poknowledge'] = {
				['travel'] = '/say travel',
				['Shadowrest'] = '/say Shadowrest',
				['reward'] = '/say reward',
			},
		},
		['Lawwe in Mourning'] = {
			['crescent'] = {
				['special'] = '/say special',
				['reflect'] = '/say reflect',
			},
		},
		['Priestess Aelea'] = {
			['crescent'] = {
				['bind'] = '/say bind',
			},
		},
		['Daer`Lagar'] = {
			['crescent'] = {
				['wood'] = '/say wood',
				['accomplished'] = '/say accomplished',
				['materials'] = '/say materials',
			},
		},
		['Sage Vilgand'] = {
			['allzones'] = {},
			['poknowledge'] = {
				['test subject'] = '/say test subject',
				['teleportation magic'] = '/say teleportation magic',
			},
		},
		['Bertrand Bibblesworth'] = {
			['poknowledge'] = {
				['crystals'] = '/say crystals',
				['trade'] = '/say trade',
			},
		},
		['Flutterwing'] = {
			['tutorialb'] = {
				['Siblings'] = '/say siblings',
			},
			['allzones'] = {},
		},
		['Initiate Dakkan'] = {
			['crescent'] = {
				['Interested'] = '/say interested',
				['learn'] = '/say learn',
				['Venom Sacs'] = '/say venom sacs',
				['Mushrooms'] = '/say mushrooms',
				['Want to try'] = '/say try',
				['Diseased Spiders'] = '/say diseased spiders',
				['Up for It'] = '/say it',
				['tasks'] = '/say tasks',
			},
		},
		['Merchant Wyn`las'] = {
			['crescent'] = {
				['city'] = '/say city',
				['traveling'] = '/say traveling',
			},
		},
		['Franklin Teek'] = {
			['allzones'] = {},
			['poknowledge'] = {
				['level 65'] = '/say level 65',
				['level 30'] = '/say level 30',
				['level 20'] = '/say level 20',
				['level 90'] = '/say level 90',
				['level 40'] = '/say level 40',
				['level 95'] = '/say level 95',
				['level 50'] = '/say level 50',
				['level 70'] = '/say level 70',
				['level 45'] = '/say level 45',
				['level 85'] = '/say level 85',
				['level 55'] = '/say level 55',
				['level 75'] = '/say level 75',
				['level 25'] = '/say level 25',
				['level 60'] = '/say level 60',
				['level 35'] = '/say level 35',
				['level 80'] = '/say level 80',
			},
		},
		['Skal Nethus'] = {
			['poknowledge'] = {
				['beasts'] = '/say beasts',
				['distressing'] = '/say distressing',
				['Dungeon Rot'] = '/say Dungeon Rot',
				['harness'] = '/say harness',
				['anger'] = '/say anger',
				['strength'] = '/say strength',
				['augment'] = '/say augment',
				['Voidsouls'] = '/say Voidsouls',
				['collect'] = '/say collect',
				['flower'] = '/say flower',
				['capture'] = '/say capture',
				['power and fortune'] = '/say power and fortune',
				['sleep'] = '/say sleep',
				['free'] = '/say free',
				['dreams'] = '/say dreams',
				['journey'] = '/say journey',
				['task'] = '/say task',
				['artifacts'] = '/say artifacts',
			},
		},
		['McKenzie the Younger'] = {
			['tutorialb'] = {
				['Lesson'] = '/say lesson',
				['Listenin'] = '/say listenin',
				['Augmentation'] = '/say augmentation',
				['embed'] = '/say embed',
			},
		},
		['Soulbinder Jera'] = {
			['poknowledge'] = {
				['Bind'] = '/say bind your soul',
			},
		},
		['Castlen Drewe'] = {
			['poknowledge'] = {
				['quest'] = '/say quest',
			},
		},
		['Vahlara'] = {
			['tutorialb'] = {
				['Others'] = '/say others',
			},
			['allzones'] = {},
		},
		['Lunya'] = {
			['poknowledge'] = {
				['aura'] = '/say aura',
			},
		},
		['Arias'] = {
			['allzones'] = {},
			['tutoriala'] = {
				['Escape'] = '/say escape',
			},
			['tutorialb'] = {
				['Wish'] = '/say wish',
			},
		},
		['Alta the Frightened'] = {
			['crescent'] = {
				['Find them'] = '/say Find them?',
				['Another'] = '/say Another who saw the baby dragons?',
				['wrong'] = '/say  what is wrong?',
				['Look for him'] = '/say I can look for him',
				['Not Here'] = '/say What do you mean not here?',
			},
		},
		['Jenn Stalbath'] = {
			['crescent'] = {
				['Blackfeather Roost'] = '/say Blackfeather Roost',
				['Each'] = '/say each',
				['Feathers'] = '/say feathers',
				['See'] = '/say see',
			},
		},
		['Historian Pewdri'] = {
			['crescent'] = {
				['traces'] = '/say traces',
				['Moors'] = '/say Moors',
				['Collect'] = '/say collect',
				['relics'] = '/say relics',
				['tower'] = '/say tower',
				['exotic remains'] = '/say exotic remains',
			},
			['allzones'] = {},
		},
	},
	['Project Lazarus'] = {
		['Mavis'] = {
			['poknowledge'] = {
				['Plane of Hate A'] = '/say Hate-A',
				['Plane of Fear'] = '/say Fear',
				['Plane of Sky'] = '/say sky',
				['None'] = '/say None',
				['Plane of Hate B'] = '/say Hate-B',
			},
		},
		['Azray Velfor'] = {
			['poknowledge'] = {
				['Cheryth Hryk'] = '/say Cheryth Hryk',
				['assist'] = '/say assist',
				['Gift of Knowledge'] = '/say Gift of Knowledge',
				['find'] = '/say find',
				['help'] = '/say help',
			},
		},
		['Sirekoth Eshe'] = {
			['allzones'] = {},
			['poknowledge'] = {
				['Sell'] = '/lootutils sellstuff',
			},
		},
		['Vierna'] = {
			['poknowledge'] = {
				['revenge'] = '/say revenge',
			},
		},
		['Klonopin'] = {
			['freeporttemple'] = {
				['Velketor\'s Labyrinth '] = '/say velketor',
				['Barindu'] = '/say barindu',
				['Vex Thal'] = '/say vexthal',
				['Plane of Nightmare'] = '/say ponightmare',
				['Wakening Lands'] = '/say wakening',
				['Befallen'] = '/say befallen',
				['Dranik'] = '/say dranik',
				['Plane of Storms'] = '/say postorms',
				['Solusek A'] = '/say soldunga',
				['Dranik\'s Scar'] = '/say draniksscar',
				['Solusek B'] = '/say soldungb',
				['Dreadlands'] = '/say dreadlands',
				['Solusek C'] = '/say soldungc',
				['Dulak'] = '/say dulak',
				['Ferubi'] = '/say ferubi',
				['Ssraeshza Temple'] = '/say ssratemple',
				['North Ro'] = '/say nro',
				['Steamfont Mountains'] = '/say steamfont',
				['Thurgadin'] = '/say thurgadina',
				['Stonebrunt Mountains'] = '/say stonebrunt',
				['The Grey'] = '/say thegrey',
				['Kurn\'s Tower'] = '/say kurn',
				['Lake of Ill Omen'] = '/say lakeofillomen',
				['Lavastorm Mountains'] = '/say lavastorm',
				['Charasis'] = '/say charasis',
				['Maiden\'s Eye'] = '/say maiden',
				['Kaesora'] = '/say kaesora',
				['Iceclad Ocean'] = '/say iceclad',
				['Cazic Thule'] = '/say cazicthule',
				['Mistmoore Castle'] = '/say mistmoore',
				['Crypt of Decay'] = '/say codecay',
				['Jagged Pine Forrest'] = '/say jaggedpine',
				['Commons'] = '/say commons',
				['Nadox'] = '/say nadox',
				['Sky Shrine'] = '/say skyshrine',
				['Emerald Jungle'] = '/say emeraldjungle',
				['Crushbone'] = '/say crushbone',
				['Najena'] = '/say najena',
				['Plane of Knowledge'] = '/say poknowledge',
				['Estate of Unrest'] = '/say unrest',
				['Dawnshroud'] = '/say dawnshroud',
				['Natimbi'] = '/say natimbi',
				['Crystal Caverns'] = '/say crystal',
				['Erudin'] = '/say erudnext',
				['Skyfire'] = '/say skyfire',
				['Necropolis'] = '/say necropolis',
				['Dalnir'] = '/say dalnir',
				['Veksar'] = '/say veksar',
				['Shar Vahl'] = '/say sharvahl',
				['North Karana'] = '/say northkarana',
				['Shadowhaven'] = '/say shadowhaven',
				['Umbral Plains'] = '/say umbral',
				['Sebilis'] = '/say sebilis',
				['Echo Caverns'] = '/say echo',
				['Scarlet Desert'] = '/say scarlet',
				['Mines of Nurga'] = '/say nurga',
				['Plane of Innovation'] = '/say poinnovation',
				['Twilight Sea'] = '/say twilight',
				['Blackburrow'] = '/say blackburrow',
				['Ocean of Tears'] = '/say oot',
				['Plane of Tactics'] = '/say potactics',
				['Western Wastes'] = '/say westwastes',
				['Bastion of Thunder'] = '/say bothunder',
				['Paludal Caverns'] = '/say paludal',
				['Plane of Valor'] = '/say povalor',
				['Plane of Water'] = '/say powater',
				['Burning Wood\'s'] = '/say burningwood',
				['Split Paw'] = '/say paw',
				['Wall of Slaughter'] = '/say wallofslaughter',
				['Warsliks Wood'] = '/say warslikswood',
				['Kael Drakkal'] = '/say kael',
				['Permafrost'] = '/say permafrost',
				['Qeynos Hills'] = '/say qeytoqrg',
				['Guk Bottom'] = '/say gukbottom',
				['Karnor\'s Castle'] = '/say karnor',
				['Plane of Air'] = '/say poair',
				['Qinimi'] = '/say qinimi',
				['Fungus Grove'] = '/say fungusgrove',
				['Chardok'] = '/say chardok',
				['Plane of Disease'] = '/say podisease',
				['Qeynos'] = '/say qrg',
				['Tower of Solusek Ro'] = '/say solrotower',
				['City of Mist'] = '/say citymist',
				['Plane of Eartha'] = '/say poeartha',
				['Riwwi'] = '/say riwwi',
				['Hole'] = '/say hole',
				['Cobalt Scar'] = '/say cobaltscar',
				['Plane of Earthb'] = '/say poearthb',
				['Runnyeye'] = '/say runnyeye',
				['South Ro'] = '/say sro',
				['The Warrens'] = '/say warrens',
				['Plane of Fire'] = '/say pofire',
				['Field of Bone'] = '/say fieldofbone',
				['Halls of Honor'] = '/say hohonora',
				['Timorous Deep'] = '/say timorous',
				['Plane of Growth'] = '/say growthplane',
				['Tower of Frozen Shadow'] = '/say frozenshadow',
				['Abysmal Sea'] = '/say abysmal',
				['Grimling Forest'] = '/say grimling',
				['None'] = '/say None',
				['Trakanon\'s Teeth'] = '/say trakanon',
				['Acrylia'] = '/say acrylia',
				['Guk Top'] = '/say guktop',
				['Plane of Justice'] = '/say pojustice',
				['Gunthak'] = '/say gunthak',
				['Arena'] = '/say arena',
				['Highkeep'] = '/say highkeep',
				['Plane of Mischief'] = '/say mischiefplane',
			},
		},
		['Magus Wenla'] = {
			['nedaria'] = {
				['North Ro'] = '/say North Ro',
				['Abysmal Sea'] = '/say Abysmal Sea',
				['Common Lands'] = '/say commonlands',
				['Natimbi'] = '/say natimbi',
				['Butcher Block'] = '/say butcherblock',
				['South Ro'] = '/say South Ro',
				['Everfrost'] = '/say everfrost',
				['None'] = '/say None',
			},
		},
		['Fipnoc Birribit'] = {
			['poknowledge'] = {
				['interesting ore'] = '/say interesting ore',
				['information'] = '/say information',
				['deal with'] = '/say deal with',
				['work'] = '/say work',
				['more'] = '/say more',
			},
		},
		['Magus Tira'] = {
			['butcherblock'] = {
				['North Ro'] = '/say North Ro',
				['Common Lands'] = '/say commonlands',
				['South Ro'] = '/say South Ro',
				['Everfrost'] = '/say everfrost',
				['None'] = '/say None',
			},
		},
		['Magus Zeir'] = {
			['ecommons'] = {
				['North Ro'] = '/say North Ro',
				['Butcher Block'] = '/say butcherblock',
				['South Ro'] = '/say South Ro',
				['Everfrost'] = '/say everfrost',
				['None'] = '/say None',
			},
		},
		['Translocator Setikan'] = {
			['freeporte'] = {
				['Ocean of Tears'] = '/say Travel to the Ocean of Tears',
				['None'] = '/say None',
			},
		},
		['Markoris'] = {
			['allzones'] = {},
			['poknowledge'] = {
				['cost'] = '/say cost',
				['train'] = '/say train',
			},
		},
		['Guardian Adiasean'] = {
			['poknowledge'] = {
				['Staff of the Four'] = '/say Staff of the Four',
			},
		},
		['Bookkeep Gerald'] = {
			['poknowledge'] = {
				['Add'] = '/say add',
				['Delete'] = '/say delete',
				['View Books'] = '/say view',
				['View Class'] = '/say view class',
				['Hide'] = '/say hide',
			},
		},
		['Rokuth'] = {
			['allzones'] = {
				['Enter Expedition'] = '/say enter',
				['Leave Expedition'] = '/say leave',
			},
		},
		['Valium'] = {
			['allzones'] = {},
			['poknowledge'] = {
				['Velketor\'s Labyrinth '] = '/say velketor',
				['Barindu'] = '/say barindu',
				['Vex Thal'] = '/say vexthal',
				['Plane of Nightmare'] = '/say ponightmare',
				['Wakening Lands'] = '/say wakening',
				['Befallen'] = '/say befallen',
				['Dranik'] = '/say dranik',
				['Plane of Storms'] = '/say postorms',
				['Solusek A'] = '/say soldunga',
				['Dranik\'s Scar'] = '/say draniksscar',
				['Solusek B'] = '/say soldungb',
				['Dreadlands'] = '/say dreadlands',
				['Solusek C'] = '/say soldungc',
				['Dulak'] = '/say dulak',
				['Ferubi'] = '/say ferubi',
				['Ssraeshza Temple'] = '/say ssratemple',
				['North Ro'] = '/say nro',
				['Steamfont Mountains'] = '/say steamfont',
				['Thurgadin'] = '/say thurgadina',
				['Stonebrunt Mountains'] = '/say stonebrunt',
				['The Grey'] = '/say thegrey',
				['Kurn\'s Tower'] = '/say kurn',
				['Lake of Ill Omen'] = '/say lakeofillomen',
				['Lavastorm Mountains'] = '/say lavastorm',
				['Kael Drakkal'] = '/say kael',
				['Maiden\'s Eye'] = '/say maiden',
				['Wall of Slaughter'] = '/say wallofslaughter',
				['Iceclad Ocean'] = '/say iceclad',
				['Charasis'] = '/say charasis',
				['Mistmoore Castle'] = '/say mistmoore',
				['Plane of Innovation'] = '/say poinnovation',
				['Jagged Pine Forrest'] = '/say jaggedpine',
				['Scarlet Desert'] = '/say scarlet',
				['Nadox'] = '/say nadox',
				['Sky Shrine'] = '/say skyshrine',
				['Emerald Jungle'] = '/say emeraldjungle',
				['Sebilis'] = '/say sebilis',
				['Najena'] = '/say najena',
				['Dawnshroud'] = '/say dawnshroud',
				['Estate of Unrest'] = '/say unrest',
				['Shadowhaven'] = '/say shadowhaven',
				['Natimbi'] = '/say natimbi',
				['Skyfire'] = '/say skyfire',
				['Erudin'] = '/say erudnext',
				['Shar Vahl'] = '/say sharvahl',
				['Necropolis'] = '/say necropolis',
				['Dalnir'] = '/say dalnir',
				['Veksar'] = '/say veksar',
				['Crystal Caverns'] = '/say crystal',
				['North Karana'] = '/say northkarana',
				['Crushbone'] = '/say crushbone',
				['Umbral Plains'] = '/say umbral',
				['Commons'] = '/say commons',
				['Echo Caverns'] = '/say echo',
				['Crypt of Decay'] = '/say codecay',
				['Mines of Nurga'] = '/say nurga',
				['Kaesora'] = '/say kaesora',
				['Twilight Sea'] = '/say twilight',
				['Blackburrow'] = '/say blackburrow',
				['Ocean of Tears'] = '/say oot',
				['Plane of Tactics'] = '/say potactics',
				['Western Wastes'] = '/say westwastes',
				['Bastion of Thunder'] = '/say bothunder',
				['Paludal Caverns'] = '/say paludal',
				['Plane of Valor'] = '/say povalor',
				['Freeport Temple'] = '/say freeporttemple',
				['Burning Wood\'s'] = '/say burningwood',
				['Split Paw'] = '/say paw',
				['Plane of Water'] = '/say powater',
				['Warsliks Wood'] = '/say warslikswood',
				['Cazic Thule'] = '/say cazicthule',
				['Permafrost'] = '/say permafrost',
				['Qeynos Hills'] = '/say qeytoqrg',
				['Guk Bottom'] = '/say gukbottom',
				['Karnor\'s Castle'] = '/say karnor',
				['Plane of Air'] = '/say poair',
				['Qinimi'] = '/say qinimi',
				['Fungus Grove'] = '/say fungusgrove',
				['Chardok'] = '/say chardok',
				['Plane of Disease'] = '/say podisease',
				['Qeynos'] = '/say qrg',
				['Tower of Solusek Ro'] = '/say solrotower',
				['City of Mist'] = '/say citymist',
				['Plane of Eartha'] = '/say poeartha',
				['Riwwi'] = '/say riwwi',
				['Hole'] = '/say hole',
				['Cobalt Scar'] = '/say cobaltscar',
				['Plane of Earthb'] = '/say poearthb',
				['Runnyeye'] = '/say runnyeye',
				['South Ro'] = '/say sro',
				['The Warrens'] = '/say warrens',
				['Plane of Fire'] = '/say pofire',
				['Field of Bone'] = '/say fieldofbone',
				['Halls of Honor'] = '/say hohonora',
				['Timorous Deep'] = '/say timorous',
				['Plane of Growth'] = '/say growthplane',
				['Tower of Frozen Shadow'] = '/say frozenshadow',
				['Abysmal Sea'] = '/say abysmal',
				['Grimling Forest'] = '/say grimling',
				['None'] = '/say None',
				['Trakanon\'s Teeth'] = '/say trakanon',
				['Acrylia'] = '/say acrylia',
				['Guk Top'] = '/say guktop',
				['Plane of Justice'] = '/say pojustice',
				['Gunthak'] = '/say gunthak',
				['Arena'] = '/say arena',
				['Highkeep'] = '/say highkeep',
				['Plane of Mischief'] = '/say mischiefplane',
			},
		},
		['Magus Delin'] = {
			['everfrost'] = {
				['North Ro'] = '/say North Ro',
				['Common Lands'] = '/say commonlands',
				['Butcher Block'] = '/say butcherblock',
				['South Ro'] = '/say South Ro',
				['None'] = '/say None',
			},
		},
		['Magus Arindri'] = {
			['nro'] = {
				['Common Lands'] = '/say commonlands',
				['Butcher Block'] = '/say butcherblock',
				['South Ro'] = '/say South Ro',
				['Everfrost'] = '/say everfrost',
				['None'] = '/say None',
			},
		},
		['Castlen Drewe'] = {
			['poknowledge'] = {
				['quest'] = '/say quest',
			},
		},
		['Translocator Fithop'] = {
			['butcherblock'] = {
				['Ocean of Tears'] = '/say Travel to the Ocean of Tears',
				['None'] = '/say None',
			},
		},
		['Rubrae'] = {
			['allzones'] = {
				['3 Hours'] = '/say 3 Hours',
				['4 Hours'] = '/say 4 Hours',
				['5 Hours'] = '/say 5 Hours',
				['6 Hours'] = '/say 6 Hours',
				['8 Hours'] = '/say 8 Hours',
				['advanced'] = '/say advanced',
				['price'] = '/say price',
				['10 Hours'] = '/say 10 Hours',
				['buffs'] = '/say buffs',
				['2 Hours'] = '/say 2 Hours',
			},
		},
		['Grynik'] = {
			['poknowledge'] = {
				['Resurrect'] = '/say resurrect',
				['Rez Corpse'] = '/say cost',
			},
		},
		['Magus Alaria'] = {
			['poknowledge'] = {
				['North Ro'] = '/say North Ro',
				['Common Lands'] = '/say commonlands',
				['Butcher Block'] = '/say butcherblock',
				['Nedaria\'s Landing'] = '/say nedaria\'s landing',
				['South Ro'] = '/say South Ro',
				['Everfrost'] = '/say everfrost',
				['None'] = '/say None',
			},
		},
		['Larat Grundror'] = {
			['poknowledge'] = {
				['lockouts'] = '/say lockouts',
			},
		},
		['A Priest of Luclin'] = {
			['poknowledge'] = {
				['Summon Corpse'] = '/say summon',
			},
		},
		['Dronk'] = {
			['poknowledge'] = {
				['efforts'] = '/say efforts',
				['task'] = '/say task',
			},
		},
		['Translocator Gethia'] = {
			['butcherblock'] = {
				['Ocean of Tears'] = '/say Travel to the Ocean of Tears',
				['None'] = '/say None',
			},
		},
		['Translocator Deela'] = {
			['timorous'] = {
				['Butcher Block'] = '/say travel to butcherblock',
				['None'] = '/say None',
			},
		},
		['Guardian Norerd'] = {
			['poknowledge'] = {
				['Spear of Fate'] = '/say Spear of Fate',
			},
		},
		['Soulbinder Jera'] = {
			['allzones'] = {
				['bind your soul'] = '/say bind your soul',
				['BIND ME'] = '/say bind your soul',
			},
			['poknowledge'] = {},
		},
		['Celli'] = {
			['bazaar'] = {
				['Temple of Marr'] = '/say Temple of Marr',
				['Plane of Knowledge'] = '/say Plane of Knowledge',
				['None'] = '/say None',
			},
		},
		['Translocator Narrik'] = {
			['oot'] = {
				['Butcher Block'] = '/say travel to butcherblock',
				['East Freeport'] = '/say travel to the Freeport',
				['None'] = '/say None',
			},
		},
		['Magus Jerira'] = {
			['sro'] = {
				['North Ro'] = '/say North Ro',
				['Common Lands'] = '/say commonlands',
				['Butcher Block'] = '/say butcherblock',
				['Everfrost'] = '/say everfrost',
				['None'] = '/say None',
			},
		},
		['Guardian Bomawyn'] = {
			['poknowledge'] = {
				['Orb of Mastery'] = '/say Orb of Mastery',
			},
		},
		['Amphrtxi'] = {
			['poknowledge'] = {
				['2 AA - > 6 DC'] = '/say convert AA 2',
				['1 AA - > 3 DC'] = '/say convert AA 1',
				['5 AA - > 15 DC'] = '/say convert AA 5',
				['convert'] = '/say convert',
				['50 AA - > 150 DC'] = '/say convert AA 50',
				['6 DC -> 2 AA'] = '/say convert DC 2',
				['15 DC -> 5 AA'] = '/say convert DC 5',
				['150 DC -> 50 AA'] = '/say convert DC 50',
				['3 DC -> 1 AA'] = '/say convert DC 1',
				['20 AA - > 60 DC'] = '/say convert AA 20',
				['30 DC -> 10 AA'] = '/say convert DC 10',
				['60 DC -> 20 AA'] = '/say convert DC 20',
				['10 AA - > 30 DC'] = '/say convert AA 10',
			},
		},
		['Montolio'] = {
			['poknowledge'] = {
				['deal'] = '/say deal',
				['days'] = '/say days',
			},
		},
		['Lazy Lady Linda'] = {
			['allzones'] = {
				['Enter AFK PoK'] = '/say enter',
				['None'] = '/say None',
			},
		},
		['Guardian Erohach'] = {
			['poknowledge'] = {
				['Fiery Defender'] = '/say Fiery Defender',
			},
		},
	},
}